
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhammad Azizi
 */
public class manageReservation extends javax.swing.JFrame {

    /**
     * Creates new form manageReservation
     */
    public manageReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReservationNumber = new javax.swing.JLabel();
        txtTicketNum = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Reservation");
        setMaximumSize(new java.awt.Dimension(1100, 520));
        setMinimumSize(new java.awt.Dimension(1100, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        lblReservationNumber.setFont(new java.awt.Font("Baby Superhero", 0, 35)); // NOI18N
        lblReservationNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblReservationNumber.setText("Ticket Number: ");
        getContentPane().add(lblReservationNumber);
        lblReservationNumber.setBounds(400, 300, 220, 40);

        txtTicketNum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtTicketNum);
        txtTicketNum.setBounds(570, 310, 260, 30);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/searchButton.png"))); // NOI18N
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(679, 360, 150, 50);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/backWhite.png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(10, 10, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/manageReservationBG.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1100, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        dispose();
        
        mainMenu main = new mainMenu();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        String seat = null, date = null, time = null, custID = null, boatID = null;
        String ic = null, name = null, address = null, phone = null, email = null, boatSeries = null;
        String ticketNum = txtTicketNum.getText();
        try
        {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/islandhopping","root","")) 
                {
                    Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT * FROM reservation WHERE revID = '" + ticketNum + "'");

                    if(rs.next())
                    {
                        seat = rs.getString(2);
                        date = rs.getString(3);
                        time = rs.getString(4);
                        custID = rs.getString(5);
                        boatID = rs.getString(6);
                        
                        Statement stmt1 = con.createStatement();
                        ResultSet rs1 = stmt1.executeQuery("SELECT * FROM customer WHERE custID = '" + custID + "'");
                        
                        if (rs1.next()) 
                        {
                            ic = rs1.getString(2);
                            name = rs1.getString(3);
                            address = rs1.getString(4);
                            phone = rs1.getString(5);
                            email = rs1.getString(6);
                        }
                        
                        Statement stmt2 = con.createStatement();
                        ResultSet rs2 = stmt2.executeQuery("SELECT * FROM boat WHERE boatID = '" + boatID + "'");
                        
                        if (rs2.next()) 
                        {
                            boatSeries = rs2.getString(2);
                        }
                        
                        Customer cust = new Customer(name, address, phone, email, ic, date, time, seat, boatSeries);
                        String display = cust.ticketDetail();
                        toDisplay(display);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "No Result Found!");
                    }
                }
                catch (SQLException e)
                {
                    System.out.println(e);
                }
        }
        catch (HeadlessException | ClassNotFoundException e)
        {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    public void toDisplay(String display)
    {
        String disp = display;
        JOptionPane.showMessageDialog(null, disp);
        
        txtTicketNum.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new manageReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblReservationNumber;
    private javax.swing.JTextField txtTicketNum;
    // End of variables declaration//GEN-END:variables
}
